FROM ubuntu:14.04
MAINTAINER Klaus Ma <madaxa@cn.ibm.com>

RUN apt-get update

RUN apt-get install curl

RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar http://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/2.52/remoting-2.52.jar \
    && chmod 755 /usr/share/jenkins \
    && chmod 644 /usr/share/jenkins/slave.jar

COPY jenkins-slave /usr/local/bin/jenkins-slave

WORKDIR /opt

ENTRYPOINT ["jenkins-slave"]
